// Code generated by entc, DO NOT EDIT.

package ent

import (
	"go-rpc-happysooner-file/internal/service/ent/file"
	"go-rpc-happysooner-file/internal/service/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescUID is the schema descriptor for uid field.
	fileDescUID := fileFields[0].Descriptor()
	// file.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	file.UIDValidator = fileDescUID.Validators[0].(func(int) error)
	// fileDescURL is the schema descriptor for url field.
	fileDescURL := fileFields[1].Descriptor()
	// file.DefaultURL holds the default value on creation for the url field.
	file.DefaultURL = fileDescURL.Default.(string)
}
