// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in go-rpc-happysooner-file/internal/service/ent/runtime.go

const (
	Version = "v0.4.0"                                          // Version of ent codegen.
	Sum     = "h1:7k+LsvK5Sq4yx/NHqdEgAsOpVeVxChmo4peBljpp6OA=" // Sum of ent codegen.
)
