name: build

on: push

jobs:
  build:
    name: docker
    runs-on: ubuntu-latest
    env:
      REGISTRY: "registry.cn-hongkong.aliyuncs.com"
      TAG: "unliar/app-happysooner-file-rpc:latest"
    steps:
      - name: "复制文件"
        uses: actions/checkout@v1
      - name: "列出文件"
        run: ls
      - name: "容器构建"
        run: |
          docker login --username=${{ secrets.ALIYUN_DOCKER_NAME }} $REGISTRY --password=${{ secrets.ALIYUN_DOCKER_PASS }}
          docker build -t build:latest .
          docker tag build:latest $REGISTRY/$TAG
          docker push $REGISTRY/$TAG
      - name: "构建失败 - 通知远浅排查问题"
        if: failure()
        run: curl -H "Content-Type:application/json" -X POST ${{ secrets.SEND_MAIL_API }} -d '{"text":"【文件服务 RPC】 构建失败", "desp":"构建失败啦! https://github.com/${{ github.repository }}/actions","to":"${{ secrets.EMAIL }}"}'
      - name: "构建成功 - 通知远浅让他开心"
        if: success()
        run: curl -H "Content-Type:application/json" -X POST ${{ secrets.SEND_MAIL_API }} -d '{"text":"【文件服务 RPC】 叮叮当当的构建成功~!", "desp":"服务更新~ https://github.com/${{ github.repository }}/actions","to":"${{ secrets.EMAIL }}"}'
#      - name: "构建成功 - 通知服务集群更新服务"
#        if: success()
#        run: curl -X POST ${{ secrets.DOCKER_HOOK }}
